config/routes.rb
Rails.application.routes.draw do
  # get 'cars/index'
  #
  # get 'cars/new'
  #
  # get 'cars/edit'
  #
  # get 'cars/show'

  root 'dealerships#index'

  # get 'dealerships/new'
  #
  # get 'dealerships/edit'
  #
  # get 'dealerships/show'

  resources :dealerships do
    resources :cars
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  validates_presence_of :make, :price, :model

  belongs_to :dealership

  def info
    "#{year} - #{make} #{model}"
  end

  def self.by_make
    order(:make)
  end
  
end

app/models/dealership.rb
class Dealership < ApplicationRecord
  validates_presence_of :name, :amount_of_cars, :second_hand

  has_many :cars

  def cars_count
    "#{name} - #{amount_of_cars} Cars Available"
  end

  def self.by_name
    order(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_dealership
  before_action :set_car, only: [:edit, :update, :show, :destroy]

  def index
    @cars = @dealership.cars
  end

  def new
    @car = @dealership.cars.new
  end

  def create
    @car = @dealership.cars.new(car_params)
    if @car.save
      flash[:success] = 'Car Created Succesfully!'
      redirect_to dealership_car_path(@dealership, @car)
    else
      flash[:error] = 'Fix errors and try again'
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      flash[:success] = 'Car Updated Succesfully!'
      redirect_to dealership_car_path(@dealership, @car)
    else
      flash[:error] = 'Fix errors and try again'
      render :edit
    end
  end

  def show
  end

  def destroy
    @car.destroy
    flash[:success] = 'Car Successfully Deleted!'
    redirect_to dealership_car_path(@car)
  end

  private
  def car_params
    params.require(:car).permit(:make, :model, :year, :price, :engine, :c_type)
  end

  def set_dealership
    @dealership = Dealership.find(params[:dealership_id])
  end

  def set_car
    @car = @dealership.cars.find(params[:id])
  end
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :set_dealership, only: [:edit, :update, :show, :destroy]

  def index
    @dealerships = Dealership.all
  end

  def new
    @dealership = Dealership.new
  end

  def create
    @dealership = Dealership.new(dealership_params)
    if @dealership.save
      flash[:success] = 'Dealership Created Succesfully!'
      redirect_to dealership_path(@dealership)
    else
      flash[:error] = 'Fix errors and try again'
      render :new
    end
  end

  def edit
  end

  def update
    if @dealership.update(dealership_params)
      flash[:success] = 'Dealership Updated!'
      redirect_to dealership_path(@dealership)
    else
      flash[:error] = 'Dealership failed to update!'
      render :edit
    end
  end

  def show
  end

  def destroy
    @dealership.destroy
    flash[:success] = 'Dealership Deleted!'
    redirect_to dealerships_path
  end

  private
  def dealership_params
    params.require(:dealership).permit(:name, :amount_of_cars, :second_hand)
  end

  def set_dealership
    @dealership = Dealership.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/views/cars/edit.html.erb
<h1>Cars#edit</h1>
<p>Find me in app/views/cars/edit.html.erb</p>

<%= form_for [@dealership, @car] do |f| %>
  <%= f.label :make %>
  <%= f.text_field :make %>
  <%= f.label :model %>
  <%= f.text_field :model %>
  <%= f.label :year %>
  <%= f.text_field :year %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :engine %>
  <%= f.number_field :engine %>
  <%= f.label :c_type %>
  <%= f.text_field :c_type %>
  <%= f.submit %>
<% end %>

app/views/cars/index.html.erb
<h1>Cars#index</h1>
<p>Find me in app/views/cars/index.html.erb</p>

<% @cars.each do |car| %>
  <ul>
    <li><%= car.make %></li>
    <li><%= car.model %></li>
    <li><%= car.year %></li>
  </ul>
<% end %>

<%= link_to 'New Car', new_dealership_car_path(@dealership) %>

app/views/cars/new.html.erb
<h1>Cars#new</h1>

<%= form_for [@dealership, @car] do |f| %>
  <%= f.label :make %>
  <%= f.text_field :make %>
  <%= f.label :model %>
  <%= f.text_field :model %>
  <%= f.label :year %>
  <%= f.text_field :year %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :engine %>
  <%= f.number_field :engine %>
  <%= f.label :c_type %>
  <%= f.text_field :c_type %>
  <%= f.submit %>
<% end %>

<%= link_to 'back', :back %>

app/views/cars/show.html.erb
<h1>Cars#show</h1>
<p>Find me in app/views/cars/show.html.erb</p>

<%= @car.make %>
<%= @car.model %>
<%= @car.year %>
<%= @car.price %>
<%= @car.engine %>
<%= @car.c_type %>

<%= link_to 'Edit', edit_dealership_car_path(@dealership, @car) %>
<%= link_to 'Bakc', :back %>
<%= link_to 'home', root_path %>

app/views/dealerships/edit.html.erb
<h1>Dealerships#edit</h1>
<p>Find me in app/views/dealerships/edit.html.erb</p>

<%= form_for @dealership do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :amount_of_cars %>
  <%= f.number_field :amount_of_cars %>
  <%= f.label :second_hand %>
  <%= f.select :second_hand, options_for_select([true, false])%>
  <%= f.submit %>
<% end %>

app/views/dealerships/index.html.erb
<h1>Dealerships#index</h1>
<p>Find me in app/views/dealerships/index.html.erb</p>

<% @dealerships.each do |dealer| %>
  <ul>
    <li><%= dealer.name %></li>
    <li><%= dealer.amount_of_cars %></li>
    <li><%= dealer.second_hand %></li>
    <%= link_to 'Delete', dealership_path(dealer), method: :destroy %>
    <%= link_to 'Edit', edit_dealership_path(dealer) %>
  </ul>
<% end %>

<%= link_to 'new', new_dealership_path %>

app/views/dealerships/new.html.erb
<h1>Dealerships#new</h1>
<p>Find me in app/views/dealerships/new.html.erb</p>

<%= form_for @dealership do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :amount_of_cars %>
  <%= f.number_field :amount_of_cars %>
  <%= f.label :second_hand %>
  <%= f.select :second_hand, options_for_select([true, false])%>
  <%= f.submit %>
<% end %>

<%= link_to 'back', :back %>

app/views/dealerships/show.html.erb
<h1>Dealerships#show</h1>
<p><%= @dealership.name %></p>
<%= link_to 'Delete', dealership_path(@dealership), method: :destroy %>
<%= link_to 'Edit', edit_dealership_path(@dealership) %>
<%= link_to 'Car_index', dealership_cars_path(@dealership) %>
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>